Repository MIT-AI-Accelerator/c3po-model-server, pull requests merged in 2024-08, with the labels that each got.

#231 feat/add-bot-info-type
  app/mattermost/crud/crud_mattermost.py
  poetry.lock
  ppg-common/ppg/schemas/mattermost/mattermost_documents.py
  ppg-common/setup.py
Labels: enhancement

#233 feat/topic-cleanup
  app/aimodels/bertopic/ai_services/basic_inference.py
  app/aimodels/bertopic/routers/bertopic_embedding_pretrained.py
  app/aimodels/bertopic/routers/train.py
  app/mattermost/crud/crud_mattermost.py
Labels: enhancement

#234 chore/list-minio
  app/core/minio.py
Labels: documentation

#235 Move list minio function to initial data to address P1 unittest failure.
  app/core/minio.py
  app/initial_data.py
Labels: bug
