Repository MIT-AI-Accelerator/c3po-model-server, pull requests merged in 2024-04, with the labels that each got.

#154 Fix unreachable fix_text logic and add associated tests.
  app/aimodels/bertopic/ai_services/topic_summarization.py
  tests/aimodels/bertopic/services/test_topic_summarization.py
Labels: bug

#155 chore/fix-gpg-leys
  README.md
Labels: documentation

#156 Minor edit to readme only
  README.md
Labels: documentation

#157 Revert readme change
  README.md
Labels: documentation

#158 chore/test-upstream-branch
  README.md
Labels: documentation

#161 chore/ngram-bugfix
  app/aimodels/bertopic/ai_services/weak_learning.py
Labels: bug

#162 python upgrade to 3.11.9 due to json decode errors on p1
  Dockerfile
  README.md
Labels: bug

#166 Feat/detect-topic-trends
  app/aimodels/bertopic/ai_services/basic_inference.py
  app/aimodels/bertopic/ai_services/topic_summarization.py
  app/aimodels/bertopic/ai_services/weak_learning.py
  app/aimodels/bertopic/models/bertopic_trained.py
  app/aimodels/bertopic/models/topic.py
  app/aimodels/bertopic/routers/train.py
  app/initial_data.py
  poetry.lock
  ppg-common/ppg/schemas/bertopic/bertopic_trained.py
  ppg-common/ppg/schemas/bertopic/topic.py
  ppg-common/setup.py
Labels: enhancement

#172 feat/topic-model-inference
  app/aimodels/bertopic/ai_services/basic_inference.py
  app/aimodels/bertopic/ai_services/topic_summarization.py
  app/aimodels/bertopic/routers/train.py
  app/mattermost/crud/crud_mattermost.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/aimodels/bertopic/integration/test_train.py
  tests/aimodels/bertopic/routers/test_train.py
  tests/aimodels/bertopic/services/test_topic_summarization.py
Labels: enhancement

#174 chore/reduce-train-complexity
  app/aimodels/bertopic/routers/train.py
Labels: bug
